# Generated by Django 4.0.3 on 2022-04-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
