# Generated by Django 4.0.3 on 2022-04-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_todolist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
