# Generated by Django 4.0.3 on 2022-04-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_alter_todolist_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
