# Generated by Django 4.0.3 on 2022-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todolist_app', '0005_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=20)),
                ('order', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
